"""PDF service — generate digital receipt PDFs from structured data."""

from __future__ import annotations

import io
import logging
from datetime import datetime

from fpdf import FPDF

logger = logging.getLogger(__name__)


class ReceiptPDF(FPDF):
    """Custom PDF layout for digital receipts."""

    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.cell(0, 10, "STRUK DIGITAL", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "", 9)
        self.set_text_color(120, 120, 120)
        self.cell(0, 5, "Generated by Teladan AI", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(0, 0, 0)
        self.ln(3)
        # Divider line
        self.set_draw_color(200, 200, 200)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, "Dokumen ini dibuat secara otomatis oleh Teladan AI", align="C")


def generate_receipt_pdf(data: dict) -> bytes:
    """Generate a professional digital receipt PDF from structured data.

    Args:
        data: Receipt dict with keys: no_nota, spanduk_items,
              percetakan_items, atk_items, total.

    Returns:
        Raw PDF bytes ready to upload.
    """
    pdf = ReceiptPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)

    # ── Receipt info ─────────────────────────────────────────────
    no_nota = data.get("no_nota", "Tidak Diketahui")
    total = data.get("total", "0")
    timestamp = datetime.now().strftime("%d %B %Y, %H:%M WIB")

    pdf.set_font("Helvetica", "", 10)
    pdf.cell(45, 7, "No. Nota", border=0)
    pdf.cell(5, 7, ":")
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 7, str(no_nota), new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 10)
    pdf.cell(45, 7, "Tanggal Cetak", border=0)
    pdf.cell(5, 7, ":")
    pdf.cell(0, 7, timestamp, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # ── Item categories ──────────────────────────────────────────
    categories = [
        ("SPANDUK", data.get("spanduk_items", [])),
        ("PERCETAKAN", data.get("percetakan_items", [])),
        ("ATK", data.get("atk_items", [])),
    ]

    for cat_name, items in categories:
        if not items:
            continue

        # Category header
        pdf.set_fill_color(240, 240, 240)
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 8, f"  {cat_name}", fill=True, new_x="LMARGIN", new_y="NEXT")

        # Table header
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_fill_color(70, 130, 180)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(15, 7, "No.", border=1, fill=True, align="C")
        pdf.cell(0, 7, "Nama Item", border=1, fill=True, new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(0, 0, 0)

        # Table rows
        pdf.set_font("Helvetica", "", 9)
        for idx, item in enumerate(items, 1):
            # Alternate row colors
            if idx % 2 == 0:
                pdf.set_fill_color(248, 248, 248)
                fill = True
            else:
                fill = False

            pdf.cell(15, 7, str(idx), border=1, fill=fill, align="C")
            pdf.cell(0, 7, str(item), border=1, fill=fill, new_x="LMARGIN", new_y="NEXT")

        pdf.ln(3)

    # ── Total ────────────────────────────────────────────────────
    pdf.ln(2)
    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)

    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(45, 10, "TOTAL")
    pdf.cell(5, 10, ":")
    pdf.set_text_color(0, 100, 0)
    pdf.cell(0, 10, f"Rp {total}", new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)

    # ── Output as bytes ──────────────────────────────────────────
    buffer = io.BytesIO()
    pdf.output(buffer)
    pdf_bytes = buffer.getvalue()
    buffer.close()

    logger.info("Generated receipt PDF (%d bytes) for nota %s", len(pdf_bytes), no_nota)
    return pdf_bytes
